### ISSUE TITLE
Manage inventory page

### ISSUE THREAD

**Issue by iMMQN** [anvilglobaldynamics/torque#1071]
Note: 1 page for both outlet and warehouse. 

## ToDo

- [x] Title; Manage Inventories 

- [x] Sidebar "Inventory", Bangla পণ্য তালিকা  

- [x] Outlet List container 

- [x] POS and view button on outlets

- [x] Warehouse List container 

- [x] view button on warehouses 

## Check 

- [x] No pagination required for now

### Queries 

1. What about privileges 'PRIV_VIEW_ALL_OUTLETS' and 'PRIV_VIEW_ALL_WAREHOUSES'?
2. What todo with module 'MOD_PRODUCT'?
