### ISSUE TITLE
Search in Lipi app

### ISSUE THREAD

**Issue by iMMQN** [anvilglobaldynamics/torque#1167]
- A search bar in home page
- Searching shows 4-5 results
- Results are basically actions a user can perform in Lipi 

Example - add product, view inventory, view income statement etc

### TODO
- [x] `elem-app-wide-search`
- [x] Language switching support
- [x] Simplify adding verses/actions
- [ ] Populate verses/actions
- [ ] Stylize (maybe in a card)

Partner document - https://docs.google.com/document/d/1_Vq-7CSKg_W8HpcnkGuOVx9fte0pUzvj1LKtukEl7xo/edit
