### ISSUE TITLE
Remove location input for outlet

### ISSUE THREAD

**Issue by iShafayet** [anvilglobaldynamics/torque#1170]
### TODO

- [x] Remove location input area from outlet
- [x] Remove "reviewOutlet" task from self-onboarding
- [x] Check and remove use of geolocation throughout app
- [x] Remove "location not updated" checking on admin panel

Note:
1. page-select-geolocation is unlinked from torque-app.html, so it won't be loaded in client side. The page is still kept.
2. We do not take location in outlet
3. Utility methods like `_showLocationDialog` are kept
