### ISSUE TITLE
Server Coding and Style Fixes - CheckList

### ISSUE THREAD

**Issue by iShafayet** [anvilglobaldynamics/torque#38]
- [ ] Delete using `_deleteDocById`.
- [ ] Call `if (!_ensureUpdate(err, wasUpdated, collectionName)) return;` after updating.
- [ ] Call `if (!_ensureDoc(err, doc, errorCode, errorMessage)) return;` after doing single get.
- [ ] If the same (or extremely similar) method is written in at least two apis, make a mixin.
- [ ] Single get calls should always start with `find`. (i.e. `_findCustomer` or `findCustomerById`, `findById` etc..)
- [ ] get calls that return a list should always start with `list`. (i.e. `_listCustomers` or `listCustomersById`, `listByIdList`, `listByCustomerIdList` etc.)
- [ ] Known errors are changed in `Api#_transformKnownError`. Add new known errors there. Simply call `this.fail(err)` elsewhere.
- [ ] Consistent Object as parameter passing.
