### ISSUE TITLE
Move lipi-server to Compute Engine

### ISSUE THREAD

**Issue by iShafayet** [anvilglobaldynamics/torque#638]
## Tasks

- [x] Prepare VPS
- [x] Update DNS
- [x] Configure pm2
- [ ] ~Figure out a way to view logs remotely~ Moved to #643
- [x] Figure out a way to view stats remotely (candidate - my-netdata.io )
- [x] Make sure vertical scaling works
- [x] Stress test
- [x] Delete lipi-server on app-engine
- [x] Clean Documentation

### Later
- [ ] ~Code and configure auto updater~ Moved to #644
