### ISSUE TITLE
facilitate businesses selling in outlet pos and delivering from warehouse

### ISSUE THREAD

**Issue by iMMQN** [anvilglobaldynamics/torque#665]
## TODO

- [x] functionality on page-pos
- [x] change sales collection and add-sales api
- [x] change sales return api
- [ ] ~show sold from warehouse name in sales record~
- [x] add module `MOD_SELL_WAREHOUSE_PRODUCTS`
- [x] make sure tests pass
- [ ] write tests simulating the situation
- [x] make sure offline sales works (selling from warehouse is disabled on offline mode)
- [x] review texts/translation
