### ISSUE TITLE
Confirmation popup during sensitive actions

### ISSUE THREAD

**Issue by iMMQN** [anvilglobaldynamics/torque#762]
### Example
![image](https://user-images.githubusercontent.com/12131543/60076133-9bde7e00-9748-11e9-820f-cecafe375496.png)

## To-Do

- [x] add-products to inventory

- [x] inventory products transfer 

- [x] edit-service-blueprint
