### ISSUE TITLE
Product Sales Report (Show which product sell more and which sell less)

### ISSUE THREAD

**Issue by iMMQN** [anvilglobaldynamics/torque#838]
### Filtering
- Filter by Product Category List or Filter by Product Blueprint List. 
  Filtering by multiple Product Category will only show products belonging to all of the product categories.
- Filter by Outlet (optional)
- Filter by Date Range

### Output
A table showing total on top.

**Columns**
1. Product Blueprint 
2. Count Sold
3. Total Sale Price

### TODO
- [x] Create Api `report-product-sales-details`
- [x] Create basic test
- [x] Create doc
- [x] Create Client UI
