### ISSUE TITLE
Plan and Execute send and resend receipts via Email

### ISSUE THREAD

**Issue by iMMQN** [anvilglobaldynamics/torque#916]
Main #890

- Only anti spamming limit

## Todo

**Part 1**
~Device check for sms receipt~ 
~Copy sms related code from torque-lite client to torque client~

- [x] Add note in customer information section, why customer info is required 
- [x] In receipt popup, ask for "email", ~"sms" (only on android),~ "printed", "no receipt"
- [x] Move receipt related code to `sales-mixin` from `lite-add-sales`
- [x] Update `add-sales` to create receipt and take parameter "sentVia"

**Part 2**
- [x] `resend-sales-receipt` api
- [x] doc
- [x] Resend receipt UI on torque client

**Part 3** 
- [x] Admin panel receipt count 
- [x] show `due` in receipt

### Note
1. Same 'receipt' collection and API can be used in lipi.shop receipt preview
