### ISSUE TITLE
Do now allow editing/modifying of digital receipts after sales (immutable digital receipts)

### ISSUE THREAD

**Issue by iShafayet** [anvilglobaldynamics/torque#936]
### TODO

- [x] Update `lite-add-sales` api so that it generates the receipt data at the time of sales.
- [x] `lite-get-receipt` api will return the pre-generated receipt json
- [x] Document the change to db 

### Questions
1. What happens to existing receipts already sent by shopkeepers?
2. What happens if we sales is discarded or returned? (An issue for when we introduce receipts in Lipi for Business)
